### PR TITLE
Fix bugs in 10.0.0

### LINKED ISSUE #111: UWP app launch/enumeration broken on Windows Desktop
It expects no auth, which is uncommon

### LINKED ISSUE #113: Delete all TaskLists / Reset Service in app is buggy
UI still shows tasklists. Not sure if it is an app issue, service issue, or both.

### LINKED ISSUE #135: Linux should check for appsettings.json in /etc/FactoryOrchestrator
This is the standard location for configuration files

### PR DESCRIPTION
**Pull request by spaceisfun**
Fixes Bug 32803715: [Watson Failure] caused by CLR_EXCEPTION_System.NullReferenceException_80004003_Microsoft.FactoryOrchestrator.Service.dll!Microsoft.FactoryOrchestrator.Service.FOService.Dispose

Fixes backwards check for DisableContainerSupport

Fixes #113 - ResetService is buggy

Fixes #135 - Support /etc/FactoryOrchestrator/appsettings.json

Fixes #111 - WDP doesn't work on Desktop

Related to #140 - Implements the workaround, but will keep the issue open until an official .NET fix is made

### CODE REVIEW

**Comment by spaceisfun** [comment]
Fixes Bug 32803715: [Watson Failure] caused by CLR_EXCEPTION_System.NullReferenceException_80004003_Microsoft.FactoryOrchestrator.Service.dll!Microsoft.FactoryOrchestrator.Service.FOService.Dispose

**Review by NeilSandlin — APPROVED** [review]

**Comment by spaceisfun** [comment]
completing, as Neil is MS FTE but github is propagating his organization update sloowly

**Pull request merged**
