### PR TITLE
Update documentation for appsettings.json & linux support

### PR DESCRIPTION
**Pull request by spaceisfun**
Also renames a few service settings for ease of use & clarity

### CODE REVIEW

**Comment by spaceisfun** [comment]
@patelp3989 can you update https://github.com/microsoft/FactoryOrchestrator/blob/0d989ed4b95ab0bdbf127964d7f236092527df1a/docs/docs/service-configuration.md with the new options for SSL? I think you will be able to checkout and push to my branch, lmk if thats not true.

**Comment by spaceisfun** [comment]
> @patelp3989 can you update https://github.com/microsoft/FactoryOrchestrator/blob/0d989ed4b95ab0bdbf127964d7f236092527df1a/docs/docs/service-configuration.md with the new options for SSL? I think you will be able to checkout and push to my branch, lmk if thats not true.

also ok if you want to do that after this PR is in...

**Comment by hajya** [comment]
👏🏽

**Pull request merged**
